// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');
const prettierConfig = require('eslint-config-prettier/flat');

module.exports = defineConfig([
  expoConfig,
  prettierConfig,
  {
    // Generated by drizzle-kit; .sql imports and formatting are not ours to police.
    ignores: ['dist/*', '.expo/*', 'src/db/migrations/*'],
  },
  {
    // Scoped to TS: eslint-config-expo only registers @typescript-eslint for these files.
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
]);
