export { db, sqliteDb, DATABASE_NAME, schema, type Db } from './client';
export { bumpDataVersion, useDataVersion } from './data-version';
export { useDatabase, type DatabaseState } from './use-database';
export { useDataFreshness } from './use-data-freshness';
export { useDbQuery, type DbQueryResult } from './use-db-query';
export { getLogCounts, useLogCounts, type LogCounts } from './use-counts';
export { useSettings, type UseSettingsResult } from './use-settings';
export { clearAllData, seedDevData, seedExerciseLibrary, type DevSeedResult } from './seed';
export { normalizeExerciseName, STARTER_EXERCISES } from './exercise-library';
export * from './queries';
